name: 'Release server app'
description: 'Release server app'
inputs:
  branch:
    description: 'The release branch to checkout'
    required: false
    default: 'master'
  version:
    description: 'Version to release'
    required: false
    default: ''
  githubUserName:
    description: 'Github username to commit'
    required: false
  githubUserEmail:
    description: 'Github user email to commit'
    required: false
  githubToken:
    description: 'The token used to checkout the repo'
    required: true
  marketplaceUser:
    description: 'The marketplace user'
    required: false
  marketplaceToken:
    description: 'The marketplace token'
    required: false
  azureToken:
    description: 'Azure artifactory token'
    required: true
  releaseNotesDirectory:
    description: 'Release notes directory'
    required: false
    default: 'release-notes'

runs:
  using: 'composite'
  steps:
    - name: Perform release
      id: perform-release
      uses: AlexeyPetrusenko/atlassian-marketplace/rerform-release@master
      with:
        branch: ${{ inputs.branch }}
        version: ${{ inputs.version }}
        githubUserName: ${{ inputs.githubUserName }}
        githubUserEmail: ${{ inputs.githubUserEmail }}
        azureToken: ${{ inputs.azureToken }}

#    - name: Verify release tag
#      id: verify-release-tag
#      uses: AlexeyPetrusenko/atlassian-marketplace/verify-release-tag@master
#      with:
#        branch: ${{ inputs.branch }}
#        githubToken: ${{ inputs.githubToken }}
#
#    - name: Setup node environment
#      id: setup-node-env
#      uses: AlexeyPetrusenko/atlassian-marketplace/setup-node@master

    - name: Build and upload jar files to release assets
      id: build-jar
      uses: AlexeyPetrusenko/atlassian-marketplace/build-tag@master
      with:
        tag: ${{ steps.perform-release.outputs.released-tag }}
        githubToken: ${{ inputs.githubToken }}

#    - name: Build and upload jar files to release assets
#      id: build-jar
#      uses: AlexeyPetrusenko/atlassian-marketplace/build-jar@master
#      with:
#        release-version: ${{ steps.verify-release-tag.outputs.release-version }}
#        branch: ${{ inputs.branch }}
#        githubToken: ${{ inputs.githubToken }}

    - name: Publish to marketplace
      id: markeplace
      uses: AlexeyPetrusenko/atlassian-marketplace/marketplace@master
      with:
        addonKey: ${{ steps.build-jar.outputs.addon-key }}
        filePath: ${{ steps.build-jar.outputs.file-path }}
        fileName: ${{ steps.build-jar.outputs.file-name }}
        version: ${{ steps.build-jar.outputs.version }}
        marketplaceUser: ${{ inputs.marketplaceUser }}
        marketplaceToken: ${{ inputs.marketplaceToken }}

    - name: Get release notes
      id: release-notes
      uses: AlexeyPetrusenko/atlassian-marketplace/get-release-notes@master
      with:
        tag: ${{ steps.perform-release.outputs.released-tag }}
        releaseNotesDirectory: ${{ inputs.releaseNotesDirectory }}

    - name: Echo notes
      run: echo "${{ steps.release-notes.outputs.notes }}"
      shell: bash

#
#    - name: Commit the changes to pom.xml
#      run: |
#        git stash apply
#        git config --global user.name "${{ inputs.githubUserName }}"
#        git config --global user.email "${{ inputs.githubUserEmail }}"
#        git add pom.xml
#        git commit -m "Bumped version to ${{ steps.verify-release-tag.outputs.release-version }}"
#        git push
#      if: steps.build-jar.outputs.should-bump-version == 'true'
#      shell: bash
